-- Full schema rebuild for Finance Monitoring.
-- Recreates every table the app needs after accidental database deletion.
-- Safe to re-run: uses "if not exists" everywhere.

-- 1. profile: custom auth (username/email + bcrypt password), one row per user
create table if not exists public.profile (
  id integer generated by default as identity primary key,
  username text not null,
  full_name text,
  email text,
  password text not null,
  avatar_url text,
  created timestamptz not null default now(),
  net_worth numeric(12, 2) not null default 0,
  allowance_balance numeric(12, 2) not null default 0,
  net_worth_pin_hash text,
  net_worth_pin_required boolean not null default true
);

comment on table public.profile is 'App user accounts with custom username/password auth.';
comment on column public.profile.password is 'Bcrypt hash of the user password.';
comment on column public.profile.net_worth_pin_hash is 'Bcrypt hash of 6-digit PIN for protected balances.';
comment on column public.profile.net_worth_pin_required is 'When true, user must enter PIN to reveal Grand Net Worth.';

create unique index if not exists profile_username_lower_idx
  on public.profile (lower(username));

create index if not exists profile_email_lower_idx
  on public.profile (lower(email));

-- 2. balance_cards: dynamic cards holding user funds
create table if not exists public.balance_cards (
  id bigint generated by default as identity primary key,
  profile_id integer not null references public.profile (id) on delete cascade,
  name text not null,
  balance numeric(12, 2) not null default 0 check (balance >= 0),
  is_hidden boolean not null default false,
  pin_hash text,
  pin_required boolean not null default true,
  sort_order integer not null default 0,
  color_theme text not null default 'sky',
  created_at timestamptz not null default now()
);

comment on table public.balance_cards is 'User-defined balance cards (e.g. Net Worth, Allowance).';

create index if not exists balance_cards_profile_id_idx
  on public.balance_cards (profile_id);

create index if not exists balance_cards_sort_order_idx
  on public.balance_cards (profile_id, sort_order);

-- 3. transactions: deposits (+) and expenses (-) against a card
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  profile_id integer not null references public.profile (id) on delete cascade,
  type text not null check (type in ('deposit', 'expense')),
  amount numeric(12, 2) not null check (amount > 0),
  description text not null,
  category text,
  deduct_from text
    check (deduct_from is null or deduct_from in ('allowance', 'net_worth')),
  card_id bigint references public.balance_cards (id),
  created_at timestamptz not null default now()
);

comment on table public.transactions is 'Deposits and expenses per balance card.';

create index if not exists transactions_profile_id_idx
  on public.transactions (profile_id);

create index if not exists transactions_created_at_idx
  on public.transactions (created_at desc);

-- 4. fund_transfers: card-to-card moves
create table if not exists public.fund_transfers (
  id bigint generated by default as identity primary key,
  profile_id integer not null references public.profile (id) on delete cascade,
  direction text
    check (direction is null or direction in ('to_allowance', 'to_net_worth')),
  amount numeric(12, 2) not null check (amount > 0),
  from_card_id bigint references public.balance_cards (id),
  to_card_id bigint references public.balance_cards (id),
  created_at timestamptz not null default now()
);

comment on table public.fund_transfers is 'Records transfers between balance cards.';

create index if not exists fund_transfers_profile_id_idx
  on public.fund_transfers (profile_id);

create index if not exists fund_transfers_created_at_idx
  on public.fund_transfers (created_at desc);

-- 5. password_reset_otps: one-time codes for forgot-password flow
create table if not exists public.password_reset_otps (
  id bigint generated by default as identity primary key,
  profile_id integer not null references public.profile (id) on delete cascade,
  code_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

comment on table public.password_reset_otps is 'Hashed one-time codes for password reset via email.';

create index if not exists password_reset_otps_profile_id_idx
  on public.password_reset_otps (profile_id);

create index if not exists password_reset_otps_expires_at_idx
  on public.password_reset_otps (expires_at desc);

-- 6. Security: RLS on, no anon/authenticated access.
-- The app talks to the DB with the service role from the server only.
alter table public.profile enable row level security;
alter table public.balance_cards enable row level security;
alter table public.transactions enable row level security;
alter table public.fund_transfers enable row level security;
alter table public.password_reset_otps enable row level security;

revoke all on table public.profile from anon, authenticated;
revoke all on table public.balance_cards from anon, authenticated;
revoke all on table public.transactions from anon, authenticated;
revoke all on table public.fund_transfers from anon, authenticated;
revoke all on table public.password_reset_otps from anon, authenticated;

grant all on table public.profile to service_role;
grant all on table public.balance_cards to service_role;
grant all on table public.transactions to service_role;
grant all on table public.fund_transfers to service_role;
grant all on table public.password_reset_otps to service_role;

grant usage, select on sequence profile_id_seq to service_role;
grant usage, select on sequence balance_cards_id_seq to service_role;
grant usage, select on sequence transactions_id_seq to service_role;
grant usage, select on sequence fund_transfers_id_seq to service_role;
grant usage, select on sequence password_reset_otps_id_seq to service_role;

notify pgrst, 'reload schema';
