-- Dynamic balance cards, profile email, and card-based transfers/transactions

alter table public.profile
  add column if not exists email text;

update public.profile
set email = username
where email is null and username like '%@%';

create table if not exists public.balance_cards (
  id bigint generated by default as identity primary key,
  profile_id integer not null references public.profile (id) on delete cascade,
  name text not null,
  balance numeric(12, 2) not null default 0 check (balance >= 0),
  is_hidden boolean not null default false,
  pin_hash text,
  pin_required boolean not null default true,
  sort_order integer not null default 0,
  color_theme text not null default 'sky',
  created_at timestamptz not null default now()
);

create index if not exists balance_cards_profile_id_idx
  on public.balance_cards (profile_id);

create index if not exists balance_cards_sort_order_idx
  on public.balance_cards (profile_id, sort_order);

-- Migrate existing net worth / allowance into cards
do $$
declare
  p record;
begin
  for p in select * from public.profile loop
    if not exists (
      select 1 from public.balance_cards bc where bc.profile_id = p.id
    ) then
      insert into public.balance_cards (
        profile_id, name, balance, is_hidden, pin_hash, pin_required, sort_order, color_theme
      ) values (
        p.id,
        'Net Worth',
        coalesce(p.net_worth, 0),
        true,
        p.net_worth_pin_hash,
        coalesce(p.net_worth_pin_required, true),
        0,
        'violet'
      );

      insert into public.balance_cards (
        profile_id, name, balance, is_hidden, pin_required, sort_order, color_theme
      ) values (
        p.id,
        'Allowance Balance',
        coalesce(p.allowance_balance, 0),
        false,
        false,
        1,
        'sky'
      );
    end if;
  end loop;
end $$;

-- Extend fund_transfers for card-to-card moves
alter table public.fund_transfers
  add column if not exists from_card_id bigint references public.balance_cards (id),
  add column if not exists to_card_id bigint references public.balance_cards (id);

-- Backfill legacy direction-based transfers
update public.fund_transfers ft
set
  from_card_id = (
    select bc.id from public.balance_cards bc
    where bc.profile_id = ft.profile_id and bc.sort_order = 0
    limit 1
  ),
  to_card_id = (
    select bc.id from public.balance_cards bc
    where bc.profile_id = ft.profile_id and bc.sort_order = 1
    limit 1
  )
where ft.from_card_id is null
  and ft.direction = 'to_allowance';

update public.fund_transfers ft
set
  from_card_id = (
    select bc.id from public.balance_cards bc
    where bc.profile_id = ft.profile_id and bc.sort_order = 1
    limit 1
  ),
  to_card_id = (
    select bc.id from public.balance_cards bc
    where bc.profile_id = ft.profile_id and bc.sort_order = 0
    limit 1
  )
where ft.from_card_id is null
  and ft.direction = 'to_net_worth';

-- Extend transactions with card reference
alter table public.transactions
  add column if not exists card_id bigint references public.balance_cards (id);

update public.transactions t
set card_id = (
  select bc.id from public.balance_cards bc
  where bc.profile_id = t.profile_id
    and bc.sort_order = case when t.deduct_from = 'net_worth' then 0 else 1 end
  limit 1
)
where t.card_id is null;

alter table public.balance_cards enable row level security;
revoke all on table public.balance_cards from anon, authenticated;

grant all on table public.balance_cards to service_role;
grant usage, select on sequence balance_cards_id_seq to service_role;

notify pgrst, 'reload schema';
