-- Finance transactions: deposits (+) and expenses (-)

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  profile_id integer not null references public.profile (id) on delete cascade,
  type text not null check (type in ('deposit', 'expense')),
  amount numeric(12, 2) not null check (amount > 0),
  description text not null,
  category text,
  created_at timestamptz not null default now()
);

create index if not exists transactions_profile_id_idx
  on public.transactions (profile_id);

create index if not exists transactions_created_at_idx
  on public.transactions (created_at desc);

alter table public.transactions enable row level security;
