-- Transfer history between net worth and allowance balance

create table if not exists public.fund_transfers (
  id bigint generated by default as identity primary key,
  profile_id integer not null references public.profile (id) on delete cascade,
  direction text not null check (direction in ('to_allowance', 'to_net_worth')),
  amount numeric(12, 2) not null check (amount > 0),
  created_at timestamptz not null default now()
);

create index if not exists fund_transfers_profile_id_idx
  on public.fund_transfers (profile_id);

create index if not exists fund_transfers_created_at_idx
  on public.fund_transfers (created_at desc);

alter table public.fund_transfers enable row level security;

revoke all on table public.fund_transfers from anon, authenticated;

grant all on table public.fund_transfers to service_role;
grant usage, select on sequence fund_transfers_id_seq to service_role;

notify pgrst, 'reload schema';

comment on table public.fund_transfers is
  'Records transfers between net worth and allowance balance.';
