-- One-time password reset OTP codes

create table if not exists public.password_reset_otps (
  id bigint generated by default as identity primary key,
  profile_id integer not null references public.profile (id) on delete cascade,
  code_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists password_reset_otps_profile_id_idx
  on public.password_reset_otps (profile_id);

create index if not exists password_reset_otps_expires_at_idx
  on public.password_reset_otps (expires_at desc);

alter table public.password_reset_otps enable row level security;
revoke all on table public.password_reset_otps from anon, authenticated;

grant all on table public.password_reset_otps to service_role;
grant usage, select on sequence password_reset_otps_id_seq to service_role;

notify pgrst, 'reload schema';
